# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170430_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='domain',
            field=models.CharField(choices=[('INFO', 'Сведения'), ('EDUC', 'Образование'), ('GRAD', 'Выпускникам'), ('STNT', 'Образовательные стандарты'), ('PSY', 'Советы психолога')], max_length=100, verbose_name='Область распространения'),
        ),
    ]
