# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 02:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название новости')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Содержание новости')),
                ('preview_picture', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Картинка анонса')),
            ],
        ),
    ]
