# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='tags',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ключевые слова'),
        ),
    ]
