# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170409_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Education', 'Образование'), ('Testimonies', 'Свидетельства'), ('Treaty', 'Договоры'), ('Regulations', 'Правила'), ('Локальные акты', 'Локальные акты'), ('Varification', 'Акты проверки'), ('Schedule', 'Расписания'), ('Standarts', 'Стандарты'), ('Safety', 'Безопасность')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
