# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170430_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ключевые слова'),
        ),
    ]
